apiVersion: v2
name: pixie
version: 0.1.0
description: API Traffic Analyzer for Kubernetes
dependencies:
  - name: pixie-operator
    version: 0.1.7
    repository: https://artifacts.px.dev/helm_charts/operator
