apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: custom-domain-gateway
      namespace: envoy
      sectionName: https-home-assistant
  hostnames:
    - "home-assistant.tryy3.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: home-assistant-svc
          namespace: home-assistant
          port: 8123
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tryy3-dev
  namespace: envoy
spec:
  secretName: home-assistant-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: home-assistant.tryy3.dev
  dnsNames:
    - home-assistant.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer