apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pixie-key-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pixie-key-secret
    creationPolicy: Owner
  data:
    - secretKey: deploy-key
      remoteRef:
        key: secrets/pixie
        property: deploy-key
