apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibration-service-backfill
  labels:
    app: calibration-service-backfill
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calibration-service-backfill
  template:
    metadata:
      labels:
        app: calibration-service-backfill
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: calibration-service-backfill
          image: ghcr.io/tryy3/cozytemp-calibration-service:0.0.4
          env:
            - name: KAFKA_BROKERS
              value: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_CONSUMER_TOPIC
              value: "cozytemp-temperature-calibration-backfill"
            - name: KAFKA_PRODUCER_TOPIC
              value: ""
            - name: KAFKA_CONSUMER_GROUP
              value: "cozytemp-calibration-service-backfill"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: cozytemp-pg-app
                  key: fqdn-uri
          
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

