apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookup-service
  labels:
    app: lookup-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lookup-service
  template:
    metadata:
      labels:
        app: lookup-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: lookup-service
          image: ghcr.io/tryy3/SpoolmanLookupService/spoolmanlookupservice:0.0.1
          env:
            - name: KAFKA_BROKERS
              value: "kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_CONSUMER_TOPIC
              value: "3dprinter-filament-transfer-initiated"
            - name: KAFKA_PRODUCER_TOPIC
              value: "3dprinter-filament-transfer-ready"
            - name: KAFKA_CONSUMER_GROUP
              value: "spoolman-lookup-service"
            - name: SPOOLMAN_API_URL
              value: "https://spoolman.tryy3.dev"
          
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
