apiVersion: v2
name: metallb
version: 0.1.0
description: MetalLB LoadBalancer for local network access
dependencies:
  - name: metallb
    version: 0.14.8
    repository: https://metallb.github.io/metallb
