{{- define "tailscale-apps.helm" }}
  sources:
    - repoURL: {{ .repoURL }}
      chart: {{ .chart }}
      targetRevision: {{ .targetRevision }}
      {{- with .tool }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
    - repoURL: {{ .valuesRepoURL }}
      targetRevision: HEAD
      ref: values
{{- end }}
{{- define "tailscale-apps.manifest" }}
  source:
    path: {{ .path | default .name | quote }}
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
{{- end }}

{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "tailscale-apps.%s" .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ $config.spec.destination.server | quote }}
  project: default
  {{ if .type | eq "helm" }}
  {{- template "tailscale-apps.helm" . }}
  {{ else if .type | eq "manifest" }}
  {{- template "tailscale-apps.manifest" . }}
  {{ end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
{{ end -}}
