kafka-ui:
  replicaCount: 1

  yamlApplicationConfig:
    kafka:
      clusters:
        - name: kafka
          bootstrapServers: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
    
    logging:
      level:
        # root: DEBUG
        # io.kafbat.ui: DEBUG
        # reactor.netty.http.server.AccessLog: DEBUG
        # org.hibernate.validator: DEBUG

  service:
    type: ClusterIP
    port: 8080

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

