apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: inventory-service
          image: ghcr.io/tryy3/spoolmaninventoryservice:0.0.4
          env:
            - name: KAFKA_BROKERS
              value: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_CONSUMER_TOPIC
              value: "3dprinter-filament-transfer-ready"
            - name: KAFKA_PRODUCER_TOPIC
              value: "3dprinter-filament-transfer-completed"
            - name: KAFKA_CONSUMER_GROUP
              value: "spoolman-inventory-service"
            - name: SPOOLMAN_API_URL
              value: "http://spoolman-svc.spoolman.svc.cluster.local/api/v1"
          
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

