apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: spoolman-gateway
  labels:
    external-dns: enabled
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
spec:
  gatewayClassName: tailscale
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "spoolman.tryy3.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: spoolman-tryy3-dev-tls

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: spoolman-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: spoolman-gateway
      namespace: envoy
  hostnames:
    - "spoolman.tryy3.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: spoolman-svc
          namespace: spoolman
          port: 80

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spoolman-tryy3-dev
spec:
  secretName: spoolman-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: spoolman.tryy3.dev
  dnsNames:
    - spoolman.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
