longhorn:
  defaultSettings:
    defaultReplicaCount: "2"
    defaultDataPath: /var/lib/longhorn

  persistence:
    defaultClass: true
    defaultClassReplicaCount: 2
    reclaimPolicy: Delete

  ingress:
    enabled: true
    ingressClassName: cilium
    host: longhorn.local
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50083"
      omni-kube-service-exposer.sidero.dev/label: "Longhorn UI"
