apiVersion: v2
name: external-dns-local
version: 0.1.0
description: External-DNS for local network using Unbound webhook
dependencies:
  - name: external-dns
    version: 1.19.0
    repository: https://kubernetes-sigs.github.io/external-dns/
