---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json5: |-
    {
      // Enter self-hosted configuration options here.
      // https://docs.renovatebot.com/self-hosted-configuration/
      autodiscover: true,
      extends: ["config:recommended"],
      gitAuthor: 'Renovate Bot <renovate@tryy3.dev>',
      username: 'renovate',
      onboardingConfig: {
        $schema: 'https://docs.renovatebot.com/renovate-schema.json',
        extends: ['config:base']
      },
      optimizeForDisabled: true,
      persistRepoData: true,
      repositories: [
      ]
    }