apiVersion: v1
kind: Service
metadata:
  name: cozytemp-server
  labels:
    app: cozytemp-server
spec:
  type: ClusterIP
  selector:
    app: cozytemp-server
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: insights
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: web
      port: 8082
      targetPort: 8082
      protocol: TCP

