config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: master

applications:
  - name: operator
    type: helm
    namespace: tailscale
    repoURL: https://pkgs.tailscale.com/helmcharts
    valuesRepoURL: https://github.com/tryy3/omni-k8.git
    chart: tailscale-operator
    targetRevision: 1.90.6
    tool:
      helm:
        valueFiles:
          - $values/tailscale-operator/values.yaml
  - name: extra
    type: manifest
    namespace: tailscale
    repoURL: https://github.com/tryy3/homelab-k8s.git
    path: apps/tailscale-extra
    targetRevision: HEAD
