apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.19.0
          args:
            - --source=service
            - --source=crd
            - --domain-filter=tryy3.dev # (optional) limit to only example.com domains; change to match the zone you create in DNSimple.
            - --provider=dnsimple
            - --registry=txt
            - --gateway-label-filter=external-dns==enabled
            - --source=gateway-httproute
            - --domain-filter=tryy3.dev
            - --policy=sync
            - --log-level=debug
          env:
            - name: DNSIMPLE_OAUTH
              valueFrom:
                secretKeyRef:
                  name: dnsimple-oauth
                  key: oauth
            - name: DNSIMPLE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: dnsimple-oauth
                  key: account_id
            - name: DNSIMPLE_ZONES
              value: "tryy3.dev"
